import { useEffect, useState } from "react";
import { ArrowRight, Brain, Clock3, FileText, MessageCircleHeart, ShieldCheck } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import Navbar from "../components/common/Navbar"; import Sidebar from "../components/common/Sidebar"; import RiskMeter from "../components/ai/RiskMeter";
import { useAuth } from "../context/AuthContext"; import { useCase } from "../context/CaseContext";

export default function PatientDashboard() {
  const { user } = useAuth(); const { getMyCases, createCase } = useCase(); const navigate = useNavigate(); const [cases,setCases]=useState([]); const [error,setError]=useState("");
  useEffect(() => { getMyCases().then(setCases).catch(e=>setError(e.response?.data?.message||"Unable to load cases.")); }, []);
  const active = cases[0]; const progress = active?.completeness || 0; const start = async () => { try { const c=await createCase(); navigate(`/case/${c._id}`); } catch(e){setError(e.response?.data?.message||"Unable to create case.");} };
  return <div className="app-shell"><Navbar/><div className="workspace"><Sidebar/><main className="main-content"><div className="page-header"><div><span className="eyebrow">PATIENT DASHBOARD</span><h1>Good morning, {user?.name?.split(" ")[0] || "there"}.</h1><p>Let's turn your health story into useful clinical intelligence.</p></div>{active ? <Link to={`/case/${active._id}`} className="primary-button">Continue AI History <ArrowRight size={18}/></Link> : <button onClick={start} className="primary-button">Start AI History <ArrowRight size={18}/></button>}</div>{error&&<div className="form-error">{error}</div>}
    <div className="stats-grid"><div className="stat-card"><div className="stat-icon"><MessageCircleHeart/></div><span>History Progress</span><strong>{progress}%</strong><small>{active ? active.conversation?.filter(x=>x.speaker==="patient").length+" responses" : "Not started"}</small></div><div className="stat-card"><div className="stat-icon"><FileText/></div><span>Documents</span><strong>{active?.documents?.length || 0}</strong><small>Uploaded records</small></div><div className="stat-card"><div className="stat-icon"><Clock3/></div><span>Case Status</span><strong>{active?.status?.replaceAll("_"," ") || "New"}</strong><small>{active ? "Case active" : "Ready to start"}</small></div></div>
    <div className="dashboard-grid"><div className="dashboard-card ai-card"><div className="card-heading"><div><span className="eyebrow">AI CASE ENGINE</span><h2>Your intelligent case</h2></div><div className="ai-chip"><Brain size={16}/>Active</div></div><div className="ai-progress"><div className="progress-track"><div className="progress-value" style={{width:`${progress}%`}}/></div><span>{progress}%</span></div><p>AarogyaSaar asks context-aware questions based on your previous answers.</p>{active?<Link to={`/case/${active._id}`} className="secondary-button">Resume <ArrowRight size={17}/></Link>:<button onClick={start} className="secondary-button">Begin <ArrowRight size={17}/></button>}</div><div className="dashboard-card risk-card"><div className="card-heading"><div><span className="eyebrow">SAFETY SCREEN</span><h2>Current risk</h2></div></div><RiskMeter score={(active?.redFlags?.length||0)>0?70:10}/><div className="safe-note"><ShieldCheck size={17}/>{(active?.redFlags?.length||0)>0?"Potential concern detected — review recommended.":"No potential red flag detected by the AI screen."}</div></div></div>
    <div className="dashboard-card"><div className="card-heading"><div><span className="eyebrow">PREVIEW</span><h2>AI Clinical Summary</h2></div>{active&&<Link to={`/case/${active._id}/summary`} className="text-link">View full summary <ArrowRight size={16}/></Link>}</div><p className="summary-preview">{active?.aiSummary?.chiefComplaint || "Complete the conversational history to generate a clinical summary."}</p></div>
  </main></div></div>;
}
